# Generated by Django 4.1.7 on 2023-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_name_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='portrait',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
