# Generated by Django 4.2.1 on 2023-05-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
