# Generated by Django 4.1.7 on 2023-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_name_alter_client_phone_number'),
        ('services', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('salon', 'master', 'service', 'time')},
        ),
    ]
