# Generated by Django 4.2.1 on 2023-05-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review_created_at'),
        ('orders', '0008_alter_order_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('master', 'time', 'is_active')},
        ),
    ]
